name: Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on:
      group: azure-integrated-runners

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.SELF_DEPLOY_KEY }}

      - name: Setup pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest --asyncio-mode=auto test/unit
